[tool.poetry]
name = "webtiscopronoz"
version = "0.1.0"
description = ""
authors = ["daandradec <daandradec@unal.edu.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.6.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
